server:
  port: 8089
spring:
  datasource:
    url: jdbc:mysql://mysqlcontainer7000:3306/anshul100?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    application:
    name: authservice
    username: root
    password: Anshul@8445461833
    driver: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect 
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest